[package]
name = "imt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.209"
serde_derive = "1.0.209"
confy = "1.0.0"
regex = "1"
thiserror = "2.0"
anyhow = "1.0"
