[package]
name = "imt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.203"
serde_derive = "1.0.203"
confy = "0.6.1"
regex = "1"
thiserror = "1.0"
anyhow = "1.0"
